export const popularDestinations = [
  { value: "paris", label: "Paris" },
  { value: "tokyo", label: "Tokyo" },
  { value: "new-york-city", label: "New York City" },
  { value: "rome", label: "Rome" },
  { value: "london", label: "London" },
  { value: "istanbul", label: "Istanbul" },
  { value: "dubai", label: "Dubai" },
  { value: "barcelona", label: "Barcelona" },
  { value: "amsterdam", label: "Amsterdam" },
  { value: "prague", label: "Prague" },
  { value: "singapore", label: "Singapore" },
  { value: "venice", label: "Venice" },
  { value: "bangkok", label: "Bangkok" },
  { value: "rio-de-janeiro", label: "Rio de Janeiro" },
  { value: "berlin", label: "Berlin" },
  { value: "sydney", label: "Sydney" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "vienna", label: "Vienna" },
  { value: "madrid", label: "Madrid" },
  { value: "buenos-aires", label: "Buenos Aires" },
  { value: "toronto", label: "Toronto" },
  { value: "san-francisco", label: "San Francisco" },
  { value: "florence", label: "Florence" },
  { value: "moscow", label: "Moscow" },
  { value: "lisbon", label: "Lisbon" },
  { value: "seoul", label: "Seoul" },
  { value: "athens", label: "Athens" },
  { value: "budapest", label: "Budapest" },
  { value: "edinburgh", label: "Edinburgh" },
  { value: "kuala-lumpur", label: "Kuala Lumpur" },
  { value: "marrakech", label: "Marrakech" },
  { value: "vancouver", label: "Vancouver" },
  { value: "krakow", label: "Krakow" },
  { value: "cape-town", label: "Cape Town" },
  { value: "mexico-city", label: "Mexico City" },
  { value: "mumbai", label: "Mumbai" },
  { value: "st-petersburg", label: "St. Petersburg" },
  { value: "copenhagen", label: "Copenhagen" },
  { value: "dublin", label: "Dublin" },
  { value: "kyoto", label: "Kyoto" },
  { value: "munich", label: "Munich" },
  { value: "shanghai", label: "Shanghai" },
  { value: "jerusalem", label: "Jerusalem" },
  { value: "seville", label: "Seville" },
  { value: "havana", label: "Havana" },
  { value: "new-orleans", label: "New Orleans" },
  { value: "porto", label: "Porto" },
  { value: "salzburg", label: "Salzburg" },
  { value: "san-diego", label: "San Diego" },
  { value: "stockholm", label: "Stockholm" },
  { value: "bruges", label: "Bruges" },
  { value: "cusco", label: "Cusco" },
  { value: "quebec-city", label: "Quebec City" },
  { value: "zurich", label: "Zurich" },
  { value: "boston", label: "Boston" },
  { value: "naples", label: "Naples" },
  { value: "austin", label: "Austin" },
  { value: "wellington", label: "Wellington" },
  { value: "nice", label: "Nice" },
  { value: "chiang-mai", label: "Chiang Mai" },
  { value: "melbourne", label: "Melbourne" },
  { value: "kobe", label: "Kobe" },
  { value: "porto-alegre", label: "Porto Alegre" },
  { value: "reykjavik", label: "Reykjavik" },
  { value: "marseille", label: "Marseille" },
  { value: "split", label: "Split" },
  { value: "cartagena", label: "Cartagena" },
  { value: "quebec", label: "Quebec" },
  { value: "lyon", label: "Lyon" },
  { value: "tallinn", label: "Tallinn" },
  { value: "bergen", label: "Bergen" },
  { value: "helsinki", label: "Helsinki" },
  { value: "galway", label: "Galway" },
  { value: "bordeaux", label: "Bordeaux" },
  { value: "antwerp", label: "Antwerp" },
  { value: "bologna", label: "Bologna" },
  { value: "dubrovnik", label: "Dubrovnik" },
  { value: "krakow", label: "Krakow" },
  { value: "riga", label: "Riga" },
  { value: "valletta", label: "Valletta" },
  { value: "luxembourg-city", label: "Luxembourg City" },
  { value: "bratislava", label: "Bratislava" },
  { value: "ljubljana", label: "Ljubljana" },
  { value: "vilnius", label: "Vilnius" },
  { value: "zagreb", label: "Zagreb" },
  { value: "bucharest", label: "Bucharest" },
  { value: "sofia", label: "Sofia" },
  { value: "belgrade", label: "Belgrade" },
  { value: "tbilisi", label: "Tbilisi" },
  { value: "yerevan", label: "Yerevan" },
  { value: "baku", label: "Baku" },
  { value: "tirana", label: "Tirana" },
  { value: "skopje", label: "Skopje" },
  { value: "chisinau", label: "Chisinau" },
  { value: "minsk", label: "Minsk" },
  { value: "kiev", label: "Kiev" },
  { value: "odessa", label: "Odessa" },
  { value: "lviv", label: "Lviv" },
  { value: "wroclaw", label: "Wroclaw" },
  { value: "gdansk", label: "Gdansk" },
  { value: "poznan", label: "Poznan" },
];